site:
  template: standard
  updated: true
  navBar:
    links:
      - title: Courses
        link: /#courses
      - title: Events
        link: /events
      - title: Blog
        link: /blog
  brand:
    logo: /icon/torqbit.png
    description: Master the art of product building and turn your ideas into
      successful, scalable products
    ogImage: /icon/torqbit.png
    favicon: /favicon.ico
    socialLinks:
      discord: https://discord.gg/NserMXcx
      github: https://github.com/torqbit
      youtube: https://www.youtube.com/@torqbit
    name: Code Academy
    brandColor: "#7e37bc"
    title: Spreads peace and harmony
  darkMode: true
  heroSection:
    title: The Awesomest teaching platform
    description: >
      Torqbit, an open-source platform, serves as a learning management software
      that works for single person to largest educational institutions
    actionButtons:
      primary:
        label: Get Started
        link: /dashboard
      secondary:
        label: Contact Us
        link: mailto:support@torqbit.com
    banner:
      lightModePath: /img/landing/online-learning.png
      darkModePath: /img/landing/online-learning.png
      position: right
  sections:
    feature:
      featureInfo:
        featureList:
          - img: /img/landing/auth.png
            title: Authentication
            description: Configure authentication with Google, Github or any other auth
              provider supported by NextAuth
            link: /docs/auth
          - img: /img/landing/auth.png
            title: Authentication
            description: Configure authentication with Google, Github or any other auth
              provider supported by NextAuth
            link: /docs/auth
          - img: /img/landing/auth.png
            title: Email
            description: Configure authentication
        title: Features
        description: Features for the learning platform
    courses:
      enable: true
      title: Courses
      description: Courses description
    blog:
      enable: true
      title: Blogs
      description: Description on blogs
